version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile_Deployment
    ports:
      - "5009:5000"
    volumes:
      - ./backend:/source
    environment:
      FLASK_APP: server.py
  frontend:
    build: frontend/
    ports:
      - "8080:8080"
