FROM python:3

# Entry attach directory
WORKDIR /source

# Uppgrades pip
RUN pip install --upgrade pip

# Install depends
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Install Production server
RUN pip install waitress


# Starts server
ENTRYPOINT ["python3", "production.py"]
